# -*- coding: utf-8 -*-
"""ProjectPsoCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1piGSULybwUjCJ5vbKr2f2b4mmG4hDQxs
"""

import numpy as np
import math
import matplotlib.pyplot as plt

def sphere(x):
    total = 0
    for xi in x:
        total += xi**2
    return total

def rosenbrock(x):
    total = 0
    for i in range(len(x)-1):
        total += 100*(x[i]**2 - x[i+1])**2 + (1 - x[i])**2
    return total

def rastrigin(x):
    total = 0
    for xi in x:
        total += xi**2 - 10*math.cos(2*math.pi*xi) + 10
    return total

def griewank(x):
    sum_part = 0
    prod_part = 1
    for i, xi in enumerate(x):
        sum_part += xi**2 / 4000.0
        prod_part *= math.cos(xi / math.sqrt(i+1))
    return 1 + sum_part - prod_part

FUNCS = {
    "Sphere":     dict(f=sphere,     D=30, lb=-5.0,  ub= 5.0),
    "Rosenbrock": dict(f=rosenbrock, D= 2, lb=-2.0,  ub= 2.0),
    "Rastrigin":  dict(f=rastrigin,  D=20, lb=-5.0,  ub= 5.0),
    "Griewank":   dict(f=griewank,   D=30, lb=-600., ub=600.)
}

def pso(f, dim, lb, ub, n=50, kmax=100, c1=2.0, c2=2.0, track_iters=0):
    parray = np.random.uniform(lb, ub, (n, dim))
    varray = np.zeros_like(parray)

    pbest = parray.copy()
    pbest_val = []
    for i in range(n):
        val = f(pbest[i])
        pbest_val.append(val)
    pbest_val = np.array(pbest_val)

    gbest_val = pbest_val[0]
    gbest = pbest[0].copy()
    for i in range(1, n):
        if pbest_val[i] < gbest_val:
            gbest_val = pbest_val[i]
            gbest = pbest[i].copy()

    g_hist = [gbest_val]
    pos_hist = []

    for k in range(kmax):
        r1, r2 = np.random.rand(n, dim), np.random.rand(n, dim)
        varray = varray + c1*r1*(pbest - parray) + c2*r2*(gbest - parray)
        parray = parray + varray

        for i in range(n):
            for d in range(dim):
                if parray[i][d] < lb:
                    parray[i][d] = lb
                if parray[i][d] > ub:
                    parray[i][d] = ub

        vals = []
        for i in range(len(parray)):
            x = parray[i]
            v = f(x)
            vals.append(v)
        val = np.array(vals)

        for i in range(len(pbest)):
            if val[i] < pbest_val[i]:
                pbest_val[i] = val[i]
                pbest[i] = parray[i]

        for i in range(len(pbest)):
            if pbest_val[i] < gbest_val:
                gbest_val = pbest_val[i]
                gbest = pbest[i].copy()

        g_hist.append(gbest_val)

        if track_iters > 0:
          if k < track_iters:
            pos_hist.append(parray.copy())

    return gbest_val, np.array(g_hist), pos_hist


def ten_runs_summary():
    print("==== 10 runs per function ====")
    for name in FUNCS:
        spec = FUNCS[name]
        f = spec["f"]
        D = spec["D"]
        lb = spec["lb"]
        ub = spec["ub"]

        vals = []
        for run in range(10):
            result = pso(f, D, lb, ub, n=50, kmax=100, c1=2.0, c2=2.0)
            vmin = result[0]
            vals.append(vmin)
        vals = np.array(vals, dtype=float)

        print("")
        print(name, "results (10 runs):")
        for i in range(10):
            print("  run", i+1, ":", vals[i])

        mean_val = vals.mean()
        std_val = vals.std(ddof=1)
        best_val = vals.min()

        print("  mean =", mean_val)
        print("  std.dev =", std_val)
        print("  minimum =", best_val)

def contour_2d(f, lb, ub, title):
    xs = np.linspace(lb, ub, 100)
    ys = np.linspace(lb, ub, 100)

    Z = []
    for y in ys:
        row = []
        for x in xs:
            row.append(f(np.array([x, y])))
        Z.append(row)
    Z = np.array(Z)

    plt.contour(xs, ys, Z, 30)
    plt.title(title)
    plt.xlabel("x1")
    plt.ylabel("x2")
    plt.show()


def draw_all_contours():
    contour_2d(sphere, -5, 5, "Sphere (D=2)")
    contour_2d(rosenbrock, -2, 2, "Rosenbrock (D=2)")
    contour_2d(rastrigin, -5, 5, "Rastrigin (D=2)")
    contour_2d(griewank, -5, 5, "Griewank (D=2)")

def rosenbrock_agents_20_iters():
    f = rosenbrock
    D = 2
    lb = -2
    ub = 2

    result = pso(f, D, lb, ub, n=50, kmax=100, c1=2.0, c2=2.0, track_iters=20)
    pos_hist = result[2]

    xs = np.linspace(lb, ub, 100)
    ys = np.linspace(lb, ub, 100)

    Z = []
    for j in range(len(ys)):
        row = []
        for i in range(len(xs)):
            val = f(np.array([xs[i], ys[j]]))
            row.append(val)
        Z.append(row)
    Z = np.array(Z)

    for it in range(20):
        plt.contour(xs, ys, Z, 30)
        P = pos_hist[it]
        plt.scatter(P[:,0], P[:,1], s=20)
        plt.title("Rosenbrock agents after iteration " + str(it+1))
        plt.xlabel("x1")
        plt.ylabel("x2")
        plt.xlim(lb, ub)
        plt.ylim(lb, ub)
        plt.show()

def rosenbrock_convergence():
    f = rosenbrock
    D = 2
    lb = -2
    ub = 2

    result = pso(f, D, lb, ub, n=50, kmax=100, c1=2.0, c2=2.0)
    g_hist = result[1]

    x = []
    y = []
    for k in range(5, len(g_hist)):
        x.append(k)
        y.append(g_hist[k])
    plt.plot(x, y)
    plt.title("Rosenbrock convergence iteration 5..100")
    plt.xlabel("iteration k")
    plt.ylabel("f(gbest)")
    plt.grid(True)
    plt.show()

ten_runs_summary()
draw_all_contours()
rosenbrock_agents_20_iters()
rosenbrock_convergence()

